const translations = {
    ar: {
        title: 'لعبة نيم',
        gameRules: 'قواعد اللعبة:',
        rule1: 'في كل دور، يمكنك التحرك خطوات محددة نحو الهدف',
        rule2: 'الفائز هو من يصل إلى الهدف أولاً',
        rule3: 'اختر خطواتك بحكمة للفوز على الكمبيوتر',
        rule4: 'إذا تجاوزت الرقم المستهدف، ستخسر اللعبة',
        goal: 'الهدف',
        maxSteps: 'الحد الأقصى للخطوات المسموحة',
        turnChoice: 'هل تريد اللعب أولاً أم ثانياً؟',
        first: '1',
        second: '2',
        currentPosition: 'الموقع الحالي',
        yourTurn: 'دورك',
        computerTurn: 'دور الكمبيوتر',
        computerLastMove: 'آخر حركة للكمبيوتر: {steps} خطوات',
        youWon: 'لقد فزت!',
        youLost: 'لقد خسرت!',
        playAgain: 'العب مرة أخرى',
        chooseLanguage: 'اختر اللغة',
        arabic: 'العربية',
        english: 'English'
    },
    en: {
        title: 'Nim Game',
        gameRules: 'Game Rules:',
        rule1: 'On each turn, you can move a specific number of steps towards the goal',
        rule2: 'The winner is the first to reach the goal',
        rule3: 'Choose your steps wisely to beat the computer',
        rule4: 'If you exceed the target number, you lose the game',
        goal: 'Goal',
        maxSteps: 'Maximum allowed steps',
        turnChoice: 'Do you want to play first or second?',
        first: '1',
        second: '2',
        currentPosition: 'Current Position',
        yourTurn: 'Your Turn',
        computerTurn: 'Computer\'s Turn',
        computerLastMove: 'Computer\'s last move: {steps} steps',
        youWon: 'You Won!',
        youLost: 'You Lost!',
        playAgain: 'Play Again',
        chooseLanguage: 'Choose Language',
        arabic: 'العربية',
        english: 'English'
    }
};