const translations = {
    ar: {
        title: 'لعبة نيم',
        gameRules: 'قواعد اللعبة',
        rule1: 'الهدف هو الوصول إلى العدد المستهدف بالضبط.',
        rule2: 'في كل دور، يمكنك إضافة رقم من 1 إلى الحد الأقصى للخطوات.',
        rule3: 'إذا تجاوزت العدد المستهدف، تخسر.',
        rule4: 'الفائز هو من يصل إلى العدد المستهدف بالضبط.',
        goal: 'الهدف',
        maxSteps: 'الحد الأقصى للخطوات',
        currentPosition: 'الموقع الحالي',
        computerLastMove: 'آخر خطوة للكمبيوتر: {steps}',
        yourTurn: 'دورك',
        computerTurn: 'دور الكمبيوتر',
        youWon: 'لقد فزت!',
        youLost: 'لقد خسرت!',
        playAgain: 'العب مرة أخرى',
        turnChoice: 'هل تريد أن تلعب أولاً أم ثانياً؟',
        first: 'أولاً',
        second: 'ثانياً',
        chooseLanguage: 'اختر اللغة',
        arabic: 'العربية',
        english: 'English',
        vsComputer: 'ضد الكمبيوتر',
        vsPlayer: 'ضد لاعب آخر',
        player: 'اللاعب',
        turn: 'دور',
        ready: 'جاهز!',
        selectDifficulty: 'اختر المستوى',
        easy: 'سهل',
        medium: 'متوسط',
        hard: 'صعب'
    },
    en: {
        title: 'Nim Game',
        gameRules: 'Game Rules',
        rule1: 'The goal is to reach exactly the target number.',
        rule2: 'On each turn, you can add a number from 1 to the maximum steps.',
        rule3: 'If you go over the target number, you lose.',
        rule4: 'The winner is the one who reaches exactly the target number.',
        goal: 'Goal',
        maxSteps: 'Maximum Steps',
        currentPosition: 'Current Position',
        computerLastMove: 'Computer\'s last move: {steps}',
        yourTurn: 'Your Turn',
        computerTurn: 'Computer\'s Turn',
        youWon: 'You Won!',
        youLost: 'You Lost!',
        playAgain: 'Play Again',
        turnChoice: 'Do you want to play first or second?',
        first: 'First',
        second: 'Second',
        chooseLanguage: 'Choose Language',
        arabic: 'العربية',
        english: 'English',
        vsComputer: 'vs Computer',
        vsPlayer: 'vs Player',
        player: 'Player',
        turn: 'turn',
        ready: 'Ready!'
    }
};